language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install -r requirements.txt

script:
  - python -m pytest --cov
  - codecov
